### DISCUSSION TITLE
Provisioning the datasource with a local file

### DISCUSSION THREAD

**Discussion by WizBangCrash** [grafana/grafana-csv-datasource#169] [Q&A]
Hi,
I am provisioning Grafana in a docker container with your plug-in and want to provision the CSV as a local file.
Using the datasource provisioner below everything works, except once the container is up & running I have to go and edit the data source to select "Local" as is always defaults to HTTP.
Is there are an option I can add to the provisioner to tell grafana that the data source is local?
I have tried changing the url to precede the path with "file:" e.g. `file:///files/display-list.csv` and `file://files/display-list.csv`, but neither work.

```yaml
apiVersion: 1

datasources:
  - name: csv-datasource
    uid: 1257c93b-f998-438c-a784-7e90fb94fb36
    type: marcusolsson-csv-datasource
    url: /files/display-list.csv
    access: "proxy"
    basicAuth: false
    isDefault: false
    editable: true
    version: 1
```
