### ISSUE TITLE
How to configure in conf/provisioning/datasources

### ISSUE THREAD

**Issue by vsoch** [grafana/grafana-csv-datasource#223]
Hi! I'm new to setting up grafana so apologies if this is detailed somewhere. I've been able to manually set up the datasource in the GUI, but I'd like to have it automatically done on container start. I know I can do this via a yaml file in `conf/provisioning/datasources` but it's not clear to me how a local path would be defined in this space. Could docs be added for this somewhere? Thank you!

**Comment by oliviermichaelis** [comment]
Hi @vsoch !
I'm a bit late, but I've been trying the same thing. In the end, I got it to work with the following `datasource.yaml`:
```yaml
apiVersion: 1
datasources:
  - name: csv
    type: marcusolsson-csv-datasource
    uid: csv
    url: http://example.com/sample.csv
```

In my case, I'm provisioning the datasource in kubernetes with:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: csv-grafana-datasource
  namespace: grafana
  labels:
    grafana_datasource: grafana
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: csv
        type: marcusolsson-csv-datasource
        uid: csv
        url: http://example.com/sample.csv
```

I hope this will help someone else from having to reverse engineer it :)
